import { InsightMetric, Broadcast, QuickAccessItem, RecommendedAction, CriticalAlert } from '../types/home';

// Mock Insight Metrics
export const MOCK_INSIGHTS: InsightMetric[] = [
  {
    id: 'sales',
    label: 'Sales vs Target',
    value: '$2.4M',
    subtitle: 'vs $2.2M target',
    trend: 'up',
    trendValue: '+9%',
    status: 'positive',
    linkTo: '/district',
    onClick: () => alert('Navigate to Sales Dashboard'),
  },
  {
    id: 'margin',
    label: 'Gross Margin',
    value: '34.2%',
    subtitle: 'District average',
    trend: 'up',
    trendValue: '+1.2%',
    status: 'positive',
    linkTo: '/district',
  },
  {
    id: 'stores',
    label: 'Stores Below Target',
    value: '3 / 12',
    subtitle: '25% of stores',
    status: 'warning',
    actionHint: '3 need attention',
    linkTo: '/store',
    onClick: () => alert('View Underperforming Stores'),
  },
  {
    id: 'audits',
    label: 'Audits Pending',
    value: '2',
    subtitle: 'Due this week',
    status: 'warning',
    actionHint: '2 due this week',
    linkTo: '/district',
    onClick: () => alert('View Pending Audits'),
  },
  {
    id: 'alerts',
    label: 'Active Alerts',
    value: '5',
    subtitle: '2 critical',
    status: 'negative',
    actionHint: '2 critical',
    linkTo: '/home',
    onClick: () => alert('View All Alerts'),
  },
];

// Mock Broadcasts
export const MOCK_BROADCASTS: Broadcast[] = [
  {
    id: '1',
    priority: 'critical',
    title: 'Emergency Safety Protocol Update',
    description: 'All stores must implement new safety procedures immediately. Review attached guidelines and confirm compliance by end of day.',
    sender: 'Sarah Johnson',
    senderRole: 'Regional Director',
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
    dueDate: new Date(Date.now() + 6 * 60 * 60 * 1000), // Due in 6 hours
    isRead: false,
    isAcknowledged: false,
    acknowledgementType: 'Required',
    category: 'Safety',
    scope: 'District',
    scopeDetails: 'District 14',
    attachments: 2,
  },
  {
    id: '2',
    priority: 'high',
    title: 'Q2 Inventory Audit Schedule',
    description: 'District-wide inventory audits scheduled for next week. Please ensure all stores are prepared and staff are briefed.',
    sender: 'HQ Operations',
    senderRole: 'Operations Team',
    timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000),
    dueDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000), // Due in 2 days
    isRead: false,
    isAcknowledged: false,
    acknowledgementType: 'Required',
    category: 'Audit',
    scope: 'District',
    scopeDetails: 'District 14',
  },
  {
    id: '3',
    priority: 'high',
    title: 'New Product Launch - Summer Collection',
    description: 'Summer collection arrives next Monday. Review planogram updates and ensure display areas are ready.',
    sender: 'Michael Chen',
    senderRole: 'District Manager',
    timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    dueDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
    isRead: true,
    isAcknowledged: false,
    acknowledgementType: 'Optional',
    category: 'Merchandising',
    scope: 'District',
    scopeDetails: 'District 14',
  },
  {
    id: '4',
    priority: 'medium',
    title: 'Updated Training Modules Available',
    description: 'New customer service training modules are now available in the learning portal. All staff should complete by month end.',
    sender: 'HR Department',
    senderRole: 'Human Resources',
    timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    dueDate: new Date(Date.now() + 28 * 24 * 60 * 60 * 1000),
    isRead: true,
    isAcknowledged: true,
    acknowledgementType: 'Optional',
    category: 'HR',
    scope: 'District',
    scopeDetails: 'District 14',
  },
  {
    id: '5',
    priority: 'medium',
    title: 'Weekly Performance Summary',
    description: 'District performance exceeded targets this week. Great work team! Detailed breakdown attached.',
    sender: 'Analytics Team',
    senderRole: 'HQ Analytics',
    timestamp: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    isRead: false,
    isAcknowledged: false,
    acknowledgementType: 'Optional',
    category: 'Operations',
    scope: 'District',
    scopeDetails: 'District 14',
    attachments: 1,
  },
  {
    id: '6',
    priority: 'low',
    title: 'System Maintenance Notice',
    description: 'Scheduled system maintenance this Sunday 2-4 AM. POS systems will be temporarily unavailable.',
    sender: 'IT Department',
    senderRole: 'IT Support',
    timestamp: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    isRead: true,
    isAcknowledged: true,
    acknowledgementType: 'Optional',
    category: 'General',
    scope: 'Company',
    scopeDetails: 'All Locations',
  },
];

// Mock Quick Access Items
export const MOCK_QUICK_ACCESS: QuickAccessItem[] = [
  {
    id: 'district',
    label: 'My District Dashboard',
    icon: 'Home',
    onClick: () => alert('Navigate to District Dashboard'),
    roles: ['DM', 'RD'],
  },
  {
    id: 'attention',
    label: 'Stores Needing Attention',
    icon: 'TrendingUp',
    badge: 3,
    onClick: () => alert('View Stores Needing Attention'),
  },
  {
    id: 'team',
    label: 'Team Management',
    icon: 'Users',
    onClick: () => alert('Navigate to Team Management'),
    roles: ['DM', 'RD', 'ADMIN'],
  },
  {
    id: 'copilot',
    label: 'Co-Pilot',
    icon: 'Bot',
    onClick: () => alert('Navigate to Co-Pilot'),
  },
];

// Mock Recommended Actions
export const MOCK_RECOMMENDED_ACTIONS: RecommendedAction[] = [
  {
    id: '1',
    title: 'Review 3 underperforming stores',
    description: 'Stores #115, #203, #187 below target',
    priority: 'high',
    onClick: () => alert('View Underperforming Stores'),
  },
  {
    id: '2',
    title: 'Complete 2 pending audits',
    description: 'Store #145 and #198 audits due this week',
    priority: 'high',
    onClick: () => alert('View Pending Audits'),
  },
  {
    id: '3',
    title: 'Investigate compliance issue',
    description: 'Store #112 flagged for safety review',
    priority: 'high',
    onClick: () => alert('View Compliance Issues'),
  },
];

// Mock Critical Alert
export const MOCK_CRITICAL_ALERT: CriticalAlert = {
  id: 'alert-1',
  title: 'Urgent Action Required',
  message: 'Emergency safety protocol update requires immediate acknowledgment from all district managers.',
  severity: 'critical',
  timestamp: new Date(),
  actions: [
    {
      label: 'View Details',
      onClick: () => alert('View Alert Details'),
    },
    {
      label: 'Acknowledge',
      onClick: () => alert('Alert Acknowledged'),
    },
  ],
};
